baseURL = 'https://shyshy9689.github.io/'
languageCode = 'zh-cn'
title = 'shyshy的博客'
theme = 'PaperMod'
author = "shyshy"
hasCJKLanguage = true


[markup.goldmark.renderer]
  unsafe = true

[params]
  DateFormat = "2006年1月2日"

